### ISSUE TITLE
Tests can't pass under EPEL

### ISSUE THREAD

**Issue by moceap** [HOST-Oman/libraqm#140]
When I try to build 0.7.2 all tests fail. They were pass in my last try (0.7.0). 

- EPEL can tested under Redhat8 or Centos8.

- Both meson and make have the issue.

- I think the issue in python test unit. Even it works under Fedora.

- This is an example of failed test
https://kojipkgs.fedoraproject.org//work/tasks/2125/77442125/build.log

--- command ---
10:54:19 /usr/bin/python3 /builddir/build/BUILD/raqm-0.7.2/x86_64-redhat-linux-gnu/../tests/runtest.py /builddir/build/BUILD/raqm-0.7.2/tests tests/raqm-test /builddir/build/BUILD/raqm-0.7.2/tests/cursor_position_GB5.test
--- stdout ---
Testing /builddir/build/BUILD/raqm-0.7.2/tests/cursor_position_GB5.test...
['tests/raqm-test', '--bytes', '006F 006D 0061 006E 00C2 0083 006F 006D 0061 006E', '--cluster', '4', '--position', '5000', '--font', '/builddir/build/BUILD/raqm-0.7.2/tests/fonts/sha1sum/bcb3b98eb67ece19b8b709f77143d91bcb3d95eb.ttf']
--- stderr ---
Traceback (most recent call last):
  File "/builddir/build/BUILD/raqm-0.7.2/x86_64-redhat-linux-gnu/../tests/runtest.py", line 53, in <module>
    actual, ret = cmd(command)
  File "/builddir/build/BUILD/raqm-0.7.2/x86_64-redhat-linux-gnu/../tests/runtest.py", line 13, in cmd
    stderr=subprocess.PIPE, text=True)
TypeError: __init__() got an unexpected keyword argument 'text'

**Comment by khaledhosny** [comment]
Fedora seems to have libraqm 0.10.1 now, so I assume this issue is fixed.
